version: "3.9"
services:
  frontend:
    container_name: webapp
    build: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file:
      - ./frontend/.env
    restart: on-failure
    volumes:
      - "./frontend:/app"
    depends_on:
      - backend

  backend:
    container_name: restapi
    build: ./backend-captcha

  gateway:
    image: nginx
    container_name: my_gateway
    depends_on:
      - frontend
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf/
    ports:
      - 80:80
