use startup_order_db;
drop procedure if exists insertrecord;
DELIMITER $$

create PROCEDURE `insertrecord` (IN RECORD_ID_VAL int, IN FULL_NAME_VAL varchar(50), IN CELL_PHONE_VAL varchar(50) ,IN WORK_PHONE_VAL varchar(50) , IN EMAIL_VAL varchar(50), IN ADDRESS_VAL VARCHAR(100) , IN BASIC_WIDGET_ORDER_VAL int,
		IN ADVANCED_WIDGET_ORDER_VAL int, IN PROTECTION_PLAN_VAL boolean)
BEGIN

IF not exists(select RECORD_ID from ORDERTABLE WHERE RECORD_ID=RECORD_ID_VAL)
THEN
INSERT INTO ORDERTABLE(RECORD_ID, FULL_NAME, Cell_Phone, Work_Phone, Email, Address, Basic_Widget_Order, Advanced_Widget_Order, Protection_Plan) VALUES (RECORD_ID_VAL,FULL_NAME_VAL, CELL_PHONE_VAL, WORK_PHONE_VAL, EMAIL_VAL, ADDRESS_VAL, BASIC_WIDGET_ORDER_VAL, ADVANCED_WIDGET_ORDER_VAL, PROTECTION_PLAN_VAL);

END IF;

END$$

