DROP database IF EXISTS STARTUP_ORDER_DB;
CREATE database STARTUP_ORDER_DB;

USE STARTUP_ORDER_DB;

DROP TABLE IF EXISTS ORDERTABLE;
CREATE TABLE ORDERTABLE 
( RECORD_ID INT,
FULL_NAME VARCHAR(50) NOT NULL,
CELL_PHONE VARCHAR(50) NOT NULL,
WORK_PHONE VARCHAR(50),
EMAIL VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(100) NOT NULL,
BASIC_WIDGET_ORDER INT NOT NULL,
ADVANCED_WIDGET_ORDER INT NOT NULL,
PROTECTION_PLAN BOOLEAN,

 
CONSTRAINT PK_RECORD_ID primary key (RECORD_ID));