create schema DBChallenge;
use DBChallenge;

create table `startup_order`(
	`id` int(11) primary key,
    `name` varchar(50),
    `cell_phone` varchar(15),
    `work_phone` varchar(15),
    `email` varchar(50),
    `address` varchar(100),
    `basic_widget` int(4),
    `adv_widget` int(4),
    `protection_plan` boolean
);

insert into `startup_order` values(1234,'Joe Smith','405.867.5309','123.123.1234','joe_s@gmail.com','123 Vic Way, Dallas TX 75001',37,12,true);

/* these are the statements generated by the program
insert into startup_order values(1234, 'Joe Smith', '405.867.5309', '123.123.1234', 'joe_s@gmail.com', '123 Vic Way', 37, 12, true);
insert into startup_order values(23, 'James Snivy', '232.2323.2424', '323.3232.4242', 'james_s@gmail.com', '321 Big Street', 73, 21, true);
insert into startup_order values(13, 'Jonathan Pichu', '131.131.1313', '313.313.3131', 'jonathan_p@gmail.com', '131 Small Street', 13, 31, false);
*/