# Generated by Django 2.2.2 on 2019-06-10 02:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fiveHundredNumbersList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intArray', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=None, null=True), size=500)),
            ],
        ),
    ]
