# Generated by Django 2.2.2 on 2019-06-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_advancedorder_basicorder_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='advancedOrder',
        ),
        migrations.RemoveField(
            model_name='record',
            name='basicOrder',
        ),
        migrations.AddField(
            model_name='record',
            name='advancedWidgetOrder',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='basicWidgetOrder',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='advancedOrder',
        ),
        migrations.DeleteModel(
            name='basicOrder',
        ),
    ]
