# Generated by Django 2.2.2 on 2019-06-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20190610_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='recordId',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
