# Generated by Django 2.2.2 on 2019-06-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_record_recordid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='record',
        ),
    ]
