# Generated by Django 2.2.2 on 2019-06-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_delete_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordId', models.IntegerField(default=None, null=True)),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('cellphone', models.CharField(default=None, max_length=10, null=True)),
                ('workphone', models.CharField(default=None, max_length=10, null=True)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('address', models.CharField(default=None, max_length=100, null=True)),
                ('protectionPlan', models.BooleanField(default=None, null=True)),
                ('basicWidgetOrder', models.IntegerField(default=None, null=True)),
                ('advancedWidgetOrder', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
